"""Knowledge guard: does MaxGPT know about this topic, and how was it taught to be asked?

A small model answers questions similar to its training data well, but produces
nonsense on topics it never saw and can stumble on unusual wording. The guard
compares each message with the questions in the training data (TF-IDF cosine
similarity) and:

* if nothing is close enough, Max says so honestly instead of guessing, and the
  question is logged to data/unanswered.txt so you can teach Max and retrain;
* if a training question matches, the model is prompted with that wording (and,
  for follow-ups like "show me an example", with the matching earlier turns), so
  the small model answers in the setting it was trained on. The answer itself is
  always generated by MaxGPT.
"""
import difflib
import math
import re
from collections import Counter
from datetime import datetime

from .data import parse_conversations

_WORD = re.compile(r"[a-z0-9_#+.]+")
# Words that say nothing about the topic.
_STOP = set("""a an the is are was were be to of in on for and or with my your i you me it this that they
what how do does can could would should please pls tell explain about give show make write max hey hi
quick question need help some any use using way get who where when why which ok okay cool nice great yes no
yeah yep lol thanks thank bye good morning night sure alright hmm wow example examples more another again
instead also simpler shorter detail details same other one there here like want know whats two three
first last have has""".split())

# Different spellings of the same topic.
_SYNONYMS = {"js": "javascript", "py": "python", "dict": "dictionary", "dicts": "dictionary",
             "dictionaries": "dictionary", "lists": "list", "arrays": "array", "funcs": "function",
             "func": "function", "functions": "function", "repo": "repository", "db": "database",
             "errors": "error", "bug": "error", "bugs": "error", "html5": "html", "css3": "css",
             "spoken": "speak", "speaks": "speak"}


def _stem(word):
    """Very light stemming so "checker", "checking" and "checks" all match "check"."""
    for suffix in ("ing", "er", "ed", "es", "s"):
        if len(word) > len(suffix) + 3 and word.endswith(suffix) and not word.endswith("ss"):
            return word[: -len(suffix)]
    return word


def _terms(text):
    words = (w.strip(".") for w in _WORD.findall(text.lower()))
    return [_stem(_SYNONYMS.get(w, w)) for w in words if w and w not in _STOP and not w.isdigit()]


def _plain(text):
    return " ".join(_WORD.findall(text.lower()))


class KnowledgeGuard:
    def __init__(self, chat_files, threshold=0.5, log_path=None):
        self.threshold, self.log_path = threshold, log_path
        # Each entry is (text to compare against, turns to prompt the model with).
        self.singles, self.pairs = [], []
        for path in chat_files:
            with open(path, encoding="utf-8") as f:
                for conv in parse_conversations(f.read()):
                    users = [i for i, (role, _) in enumerate(conv) if role == "user"]
                    for n, i in enumerate(users):
                        prompt = conv[:i + 1]
                        if n == 0:
                            self.singles.append((conv[i][1], prompt))
                        else:  # a follow-up: remember it together with the question before it
                            self.pairs.append((conv[users[n - 1]][1] + " " + conv[i][1], prompt, conv[i][1]))
        docs = [Counter(_terms(entry[0])) for entry in self.singles + self.pairs]
        df = Counter(t for d in docs for t in d)
        n = len(docs) or 1
        self.idf = {t: math.log((1 + n) / (1 + c)) + 1 for t, c in df.items()}
        # words never seen in training weigh more than any known word: they signal a new topic
        self.unknown_idf = 1.5 * (math.log(1 + n) + 1)
        self.single_vecs = [self._vec(Counter(_terms(text))) for text, _ in self.singles]
        self.pair_vecs = [self._vec(Counter(_terms(entry[0]))) for entry in self.pairs]
        # small talk ("thanks!", "ok") has no topic words, so it is matched by its plain text
        self.small_talk = {_plain(text): prompt for text, prompt in self.singles if not _terms(text)}

    def _vec(self, counts):
        v = {t: c * self.idf.get(t, self.unknown_idf) for t, c in counts.items()}
        norm = math.sqrt(sum(x * x for x in v.values())) or 1.0
        return {t: x / norm for t, x in v.items()}

    def _best(self, text, vecs, entries, needed=None):
        """Most similar entry; with `needed`, only entries sharing one of those terms count."""
        q = self._vec(Counter(_terms(text)))
        if not any(t in self.idf for t in q):
            return 0.0, None
        best, best_entry = 0.0, None
        for vec, entry in zip(vecs, entries):
            if needed and not needed.intersection(vec):
                continue
            s = sum(w * vec.get(t, 0.0) for t, w in q.items())
            if s > best:
                best, best_entry = s, entry
        return best, best_entry

    def score(self, question):
        """Best similarity (0..1) to an opening training question, and that question."""
        if not _terms(question):
            return 1.0, None
        s, entry = self._best(question, self.single_vecs, self.singles)
        return s, entry[0] if entry else None

    def match(self, question, previous=None, context=None):
        """Turns to prompt the model with, or None if Max hasn't learned this topic.

        Returns the closest training question, or for a follow-up the matching
        training conversation up to and including the follow-up. `context` is the
        earlier conversation used to carry a topic over (defaults to `previous`).
        """
        s1, single = self._best(question, self.single_vecs, self.singles) if _terms(question) else (0.0, None)
        s2, pair = 0.0, None
        if previous:
            s2, pair = self._best(previous + " " + question, self.pair_vecs, self.pairs)
        if pair and s2 >= self.threshold and s2 >= s1 and self._similar_follow_up(question, pair[2]):
            return list(pair[1])
        context = context or previous
        carried = None
        if context and _terms(question):
            # Carry the topic over: "And its currency?" after "capital of Japan?" -> "What currency does Japan use?"
            # The extra context words lower the score, so a weaker match is fine when the training
            # question shares words with both the new question and the earlier ones.
            s3, best = self._best(context + " " + question, self.single_vecs, self.singles,
                                  needed=set(_terms(question)))
            if best and s3 >= self.threshold / 2 and set(_terms(context)) & set(_terms(best[0])):
                carried = best
        if single and s1 < self.threshold + 0.15 and not self._keeps_topic(question, single[0]):
            single = None  # "how many moons…" is not "how many bones…"
        if single and s1 >= self.threshold:
            # "What language do they speak there?" alone matches some country; prefer the one from
            # the conversation when the direct match brings in words the user never mentioned.
            said = set(_terms(question)) | set(_terms(context or ""))
            if not carried or len(set(_terms(single[0])) - said) <= len(set(_terms(carried[0])) - said):
                return list(single[1])
        if carried:
            return list(carried[1])
        if not _terms(question):  # small talk ("thanks!", "show me more")
            close = difflib.get_close_matches(_plain(question), list(self.small_talk), n=1, cutoff=0.3)
            if close:
                return list(self.small_talk[close[0]])
            return [("user", "Hello")] if "hello" in self.small_talk else [("user", question)]
        return None

    def _keeps_topic(self, question, trained):
        """Does the trained question contain the asker's most specific known word?"""
        known = [t for t in _terms(question) if t in self.idf]
        if not known:
            return True
        top = max(self.idf[t] for t in known)
        return any(self.idf[t] == top for t in set(known) & set(_terms(trained)))

    @staticmethod
    def _similar_follow_up(question, trained):
        """Is this follow-up worded like the trained one (e.g. "give me an example" ~ "Show me an example")?"""
        if set(_terms(question)) & set(_terms(trained)):
            return True
        return difflib.SequenceMatcher(None, _plain(question), _plain(trained)).ratio() >= 0.5

    def knows(self, question, previous=None):
        """True if Max has learned about this question (alone, or as a follow-up)."""
        return self.match(question, previous) is not None

    def log_unknown(self, question):
        if not self.log_path:
            return
        try:
            with open(self.log_path, "a", encoding="utf-8") as f:
                f.write(f"{datetime.now():%Y-%m-%d %H:%M}\t{question.replace(chr(10), ' ')}\n")
        except OSError:
            pass
